export default Object.fromEntries([
	"Warrior",
	"Ranger",
	"Sorceress",
	"Berserker",
	"Tamer",
	"Ninja",
	"Kunoichi",
	"Witch",
	"Wizard",
	"Maehwa",
	"Valkyrie",
	"Musa",
	"Dark Knight",
	"Striker",
	"Mystic",
	"Lahn",
	"Archer",
	"Shai",
	"Guardian",
	"Hashashin",
	"Nova",
	"Sage",
	"Corsair",
	"Drakania",
	"Woosa",
	"Maegu",
	"Scholar",
].map((className, i) => [className, `-1.98rem ${-((5.5 / 3) * i + 0.3)}rem`]))
